sudo: required
language: java
jdk: openjdk11

services:
  - docker
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - chmod +x mvnw

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 9999999

addons:
  sonarcloud:
    organization: "bracketboys"
    token: $SONAR_TOKEN

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=$SONAR_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.cpd.exclusions=**/dto/*

cache:
  yarn: true
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - export TAG=`if [ ! -z $TRAVIS_PULL_REQUEST ]; then echo $TRAVIS_PULL_REQUEST_BRANCH; else echo $TAG; fi`
  - export IMAGE_NAME=joostlek/webshop
  - docker build -t $IMAGE_NAME:$TAG .
  - docker push $IMAGE_NAME
